# Generated by Django 6.0.4 on 2026-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('git', models.URLField(blank=True, max_length=255, null=True)),
                ('linked', models.URLField(blank=True, max_length=255, null=True)),
                ('url_imagem', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
